# Generated by Django 2.2.2 on 2019-07-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('A', 'کلاس الف'), ('B', 'کلاس ب')], max_length=1, verbose_name='شماره کلاس')),
                ('education_year', models.CharField(max_length=20, null=True, verbose_name='سال تحصیلی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(blank=True, choices=[('SA', 'شنبه'), ('SU', 'یکشنبه'), ('MO', 'دوشنبه'), ('TU', 'سه شنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنجشنبه'), ('FR', 'جمعه')], max_length=2, null=True, verbose_name='روز کلاس')),
                ('class_time', models.CharField(blank=True, choices=[('FI', 'زنگ اول'), ('SE', 'زنگ دوم'), ('TH', 'زنگ سوم'), ('FO', 'زنگ چهارم')], max_length=2, null=True, verbose_name='زنگ')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام درس')),
                ('unit', models.IntegerField(null=True, verbose_name='تعداد واحد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='LevelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'پایه اول'), ('2', 'پایه دوم'), ('3', 'پایه سوم')], max_length=1, verbose_name='پایه تحصیلی')),
                ('field', models.CharField(choices=[('HU', 'علوم انسانی'), ('MA', 'علوم ریاضی'), ('NA', 'علوم تجربی')], max_length=2, verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'لیست پایه های تحصیلی',
                'verbose_name_plural': 'لیست پایه های تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید', verbose_name='فعال')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='edu.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ آخرین ویرایش')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='تصویر پروفایل')),
                ('father_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام پدر')),
                ('student_id', models.IntegerField(verbose_name='شماره دانش آموزی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('education_field', models.CharField(blank=True, choices=[('MA', 'ریاضی و فیزیک'), ('HU', 'علوم انسانی'), ('EX', 'علوم تجربی')], max_length=2, null=True, verbose_name='رشته تحصیلی')),
                ('classrooms', models.ManyToManyField(related_name='students', through='edu.Register', to='edu.Classroom', verbose_name='کلاس ها')),
            ],
            options={
                'verbose_name': 'دانش آموز',
                'verbose_name_plural': 'دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('mid_grade', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='edu.Course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='edu.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ آخرین ویرایش')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='تصویر پروفایل')),
                ('father_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام پدر')),
                ('teacher_id', models.IntegerField(verbose_name='کد پرسنلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('hire_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('edu_degree', models.CharField(choices=[('FD', 'کاردانی'), ('LI', 'کارشناسی'), ('FL', 'کارشناسی ارشد'), ('DR', 'دکتری'), ('DI', 'دیپلم')], max_length=2, verbose_name='مدرک تحصیلی')),
                ('profession', models.ManyToManyField(blank=True, to='edu.Course', verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'آموزگار',
                'verbose_name_plural': 'آموزگاران',
            },
        ),
        migrations.CreateModel(
            name='TeacherClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید', verbose_name='فعال')),
                ('class_times', models.ManyToManyField(related_name='teacher_class_course', to='edu.ClassTime', verbose_name='زمان کلاس')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Classroom', verbose_name='پایه تحصیلی')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Course', verbose_name='نام درس')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Teacher', verbose_name='نام استاد')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(verbose_name='حاضر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('class_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.ClassTime')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.StudentCourse')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='edu.StudentCourse', to='edu.Course', verbose_name='دورس '),
        ),
        migrations.AddField(
            model_name='register',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='edu.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.LevelField', verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='courses',
            field=models.ManyToManyField(related_name='classrooms', through='edu.TeacherClassCourse', to='edu.Course', verbose_name='دروس'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='level_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.LevelField', verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', through='edu.TeacherClassCourse', to='edu.Teacher', verbose_name='اساتید'),
        ),
    ]
