# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس ها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'آموزگار', 'verbose_name_plural': 'آموزگاران'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='field',
            field=models.CharField(choices=[('HU', 'علوم انسانی'), ('MA', 'علوم ریاضی'), ('NA', 'علوم تجربی')], max_length=2),
        ),
    ]
