# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20190425_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
    ]
