# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_remove_teacher_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelfield',
            options={'verbose_name': 'لیست پایه های تحصیلی', 'verbose_name_plural': 'لیست پایه های تحصیلی'},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_profiles'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='teacher_profiles'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='branch',
            field=models.CharField(choices=[('A', 'کلاس الف'), ('B', 'کلاس ب')], max_length=1, verbose_name='شماره کلاس'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='courses',
            field=models.ManyToManyField(related_name='classrooms', through='edu.TeacherClassCourse', to='edu.Course', verbose_name='دروس'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='education_year',
            field=models.CharField(max_length=20, null=True, verbose_name='سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='level_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.LevelField', verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', through='edu.TeacherClassCourse', to='edu.Teacher', verbose_name='اساتید'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.LevelField', verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.IntegerField(null=True, verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='levelfield',
            name='field',
            field=models.CharField(choices=[('HU', 'علوم انسانی'), ('MA', 'علوم ریاضی'), ('NA', 'علوم تجربی')], max_length=2, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='levelfield',
            name='level',
            field=models.CharField(choices=[('1', 'پایه اول'), ('2', 'پایه دوم'), ('3', 'پایه سوم')], max_length=1, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', through='edu.Register', to='edu.Classroom', verbose_name='کلاس ها'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='edu.StudentCourse', to='edu.Course', verbose_name='دورس '),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_modified_date',
            field=models.DateTimeField(null=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='شماره دانش آموزی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_degree',
            field=models.CharField(choices=[('FD', 'کاردانی'), ('LI', 'لیسانس'), ('FL', 'فوق لیسانس'), ('DR', 'دکتری'), ('DI', 'دیپلم')], max_length=2, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.ManyToManyField(to='edu.Course', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(verbose_name='کد پرسنلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
