# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-23 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20190521_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
