# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_auto_20190523_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='edu.Course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='mid_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='edu.Student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='class_time',
            field=models.CharField(max_length=20, verbose_name='زمان کلاس'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Classroom', verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Course', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_course', to='edu.Teacher', verbose_name='نام استاد'),
        ),
    ]
