# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20190524_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_field',
            field=models.CharField(blank=True, choices=[('MA', 'ریاضی و فیزیک'), ('HU', 'علوم انسانی'), ('EX', 'علوم تجربی')], max_length=2, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AddField(
            model_name='teacherclasscourse',
            name='class_day',
            field=models.CharField(blank=True, choices=[('MO', 'دوشنبه'), ('TU', 'سه شنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنجشنبه'), ('FR', 'جمعه'), ('SA', 'شنبه'), ('SU', 'یکشنبه')], max_length=2, null=True, verbose_name='روز کلاس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_degree',
            field=models.CharField(choices=[('FD', 'کاردانی'), ('LI', 'کارشناسی'), ('FL', 'کارشناسی ارشد'), ('DR', 'دکتری'), ('DI', 'دیپلم')], max_length=2, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='class_time',
            field=models.CharField(blank=True, choices=[('FI', 'زنگ اول'), ('SE', 'زنگ دوم'), ('TH', 'زنگ سوم'), ('FO', 'زنگ چهارم'), ('FI', 'زنگ پنجم')], max_length=2, null=True, verbose_name='زنگ'),
        ),
    ]
