# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_auto_20190527_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='تصویر پروفایل'),
        ),
    ]
