# Generated by Django 2.2.1 on 2019-05-27 15:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20190527_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='delivery_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
