# Generated by Django 2.2.1 on 2019-05-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_auto_20190528_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='delivery_date',
        ),
    ]
