# Generated by Django 2.2.1 on 2019-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_remove_student_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='class_day',
            field=models.CharField(blank=True, choices=[('SA', 'شنبه'), ('SU', 'یکشنبه'), ('MO', 'دوشنبه'), ('TU', 'سه شنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنجشنبه'), ('FR', 'جمعه')], max_length=2, null=True, verbose_name='روز کلاس'),
        ),
    ]
