# Generated by Django 2.2.2 on 2019-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_studentpresence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherclasscourse',
            old_name='class_time',
            new_name='class_times',
        ),
        migrations.AddField(
            model_name='teacherclasscourse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='class_time',
            field=models.CharField(blank=True, choices=[('FI', 'زنگ اول'), ('SE', 'زنگ دوم'), ('TH', 'زنگ سوم'), ('FO', 'زنگ چهارم')], max_length=2, null=True, verbose_name='زنگ'),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True, help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید', verbose_name='فعال'),
        ),
    ]
