# Generated by Django 2.2.2 on 2019-06-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20190629_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profession',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Course', verbose_name='تخصص'),
        ),
    ]
