# Generated by Django 2.2.2 on 2019-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_auto_20190630_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profession',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.ManyToManyField(blank=True, null=True, to='edu.Course', verbose_name='تخصص'),
        ),
    ]
